[package]
name = "crowdstress-common"
version = "0.2.0"
authors = ["Evgenii Kozlov <kozlov.work.52@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
serde = "1.0.123"
serde_derive = "1.0.123"
